[package]
name = "arcology-api"
version = "0.1.0"
authors = ["Bartłomiej Michalski"]
edition = "2018"

[dependencies]
actix-web="3.3.1"
derive_more = "0.99"
r2d2_redis = "0.14.0"
thiserror = "1.0"
env_logger = "0.8.3"
serde = ""
serde_json = "1.0.59"
derive_builder = { path = "src/builder" }
