[tasks.create]
command = "docker"
args = ["build", "-f dockerfiles/Dockerfile.dev", "."]

[tasks.stop]
command = "docker"
args = ["stop", "arcology-backend-container"]

[tasks.rundocker]
dependencies = ["stop"]
command = "docker"
args = ["run", "-p 8080:8080", "--rm", "--name arcology-backend-container", "arcology-backend"]

[tasks.up]
command = "docker-compose"
args = ["up"]

[tasks.run]
command = "cargo"
args = ["run"]